import fs from 'fs/promises';
import path from 'path';

import { SnapConfigParser, SnapServerConfig } from '../utils/snapConfigParser';
import {
  surgicallySetIniKey,
  surgicallyAddStreamSource,
  surgicallyRemoveStreamSourcesByFifo,
} from '../utils/snapConfigEdit';
import { DEFAULT_SNAPSERVER_CONF } from '../constants/defaultConfig';

// Default location on Debian
// Default locations on Debian
const SNAPSERVER_CONFIG_PATH = '/etc/snapserver.conf';
const SNAPSERVER_CONFIG_BASE = '/etc/snapserver.conf.base';
const SNAPSERVER_CONFIG_DIR = '/etc/snapserver.conf.d';

export class ConfigService {
  
  async readServerConfig(): Promise<string> {
    try {
      await fs.access(SNAPSERVER_CONFIG_PATH);
      return await fs.readFile(SNAPSERVER_CONFIG_PATH, 'utf-8');
    } catch (error) {
     console.warn(`Could not read ${SNAPSERVER_CONFIG_PATH}, returning empty.`);
     return '';
    }
  }

  async readServerConfigParsed(): Promise<SnapServerConfig> {
    const raw = await this.readServerConfig();
    return SnapConfigParser.parse(raw);
  }

  async writeServerConfigParsed(config: SnapServerConfig): Promise<void> {
    const raw = SnapConfigParser.stringify(config);
    await this.writeServerConfig(raw);
  }

  async writeServerConfig(content: string): Promise<void> {
    // If modular system is active/desired, we should probably write to base instead
    // but for compatibility with existing UI, we'll allow writing to master if requested.
    // However, the "right" way now is via segments or base.
    await fs.writeFile(SNAPSERVER_CONFIG_PATH, content, 'utf-8');
  }

  async ensureModularStructure(): Promise<void> {
    try {
      await fs.mkdir(SNAPSERVER_CONFIG_DIR, { recursive: true });
      
      try {
        await fs.access(SNAPSERVER_CONFIG_BASE);
      } catch (e) {
        // Migrate current config to base if base doesn't exist
        console.log(`Migrating ${SNAPSERVER_CONFIG_PATH} to ${SNAPSERVER_CONFIG_BASE}...`);
        const current = await this.readServerConfig();
        if (current && current.length > 50) { // arbitrary length to avoid migrating empty/broken files
          await fs.writeFile(SNAPSERVER_CONFIG_BASE, current, 'utf-8');
        } else {
          await fs.writeFile(SNAPSERVER_CONFIG_BASE, DEFAULT_SNAPSERVER_CONF, 'utf-8');
        }
      }
    } catch (error) {
      console.error('Failed to ensure modular structure:', error);
    }
  }

  async rebuildMasterConfig(): Promise<void> {
    await this.ensureModularStructure();
    
    let masterContent = '###############################################################################\n';
    masterContent += '# WARNING: THIS FILE IS AUTOMATICALLY GENERATED BY SNAPCAST MANAGER\n';
    masterContent += `# ANY MANUAL CHANGES WILL BE OVERWRITTEN. EDIT ${SNAPSERVER_CONFIG_BASE} OR SEGMENTS IN ${SNAPSERVER_CONFIG_DIR}\n`;
    masterContent += '###############################################################################\n\n';

    // 1. Read Base
    try {
      const base = await fs.readFile(SNAPSERVER_CONFIG_BASE, 'utf-8');
      masterContent += '### START BASE CONFIGURATION ###\n';
      masterContent += base;
      masterContent += '\n### END BASE CONFIGURATION ###\n\n';
    } catch (e) {
      masterContent += '# Error reading base configuration\n\n';
    }

    // 2. Read Segments
    try {
      const files = await fs.readdir(SNAPSERVER_CONFIG_DIR);
      const confFiles = files.filter(f => f.endsWith('.conf')).sort();
      
      for (const file of confFiles) {
        const content = await fs.readFile(path.join(SNAPSERVER_CONFIG_DIR, file), 'utf-8');
        masterContent += `### START SEGMENT: ${file} ###\n`;
        masterContent += content;
        masterContent += `\n### END SEGMENT: ${file} ###\n\n`;
      }
    } catch (e) {
      console.error('Error reading configuration segments:', e);
    }

    await fs.writeFile(SNAPSERVER_CONFIG_PATH, masterContent, 'utf-8');
  }

  async getSegments(): Promise<{name: string, content: string}[]> {
    await this.ensureModularStructure();
    const segments: {name: string, content: string}[] = [];
    try {
      const files = await fs.readdir(SNAPSERVER_CONFIG_DIR);
      const confFiles = files.filter(f => f.endsWith('.conf')).sort();
      
      for (const file of confFiles) {
        const content = await fs.readFile(path.join(SNAPSERVER_CONFIG_DIR, file), 'utf-8');
        segments.push({ name: file, content });
      }
    } catch (e) {
      console.error('Error listing segments:', e);
    }
    return segments;
  }

  /** Segment names come from HTTP params — never let them escape the config dir. */
  private sanitizeSegmentName(name: string): string {
    const base = path.basename(name);
    if (base !== name || base.startsWith('.') || !/^[\w.-]+$/.test(base)) {
      throw new Error(`Invalid segment name: ${name}`);
    }
    return base;
  }

  async saveSegment(name: string, content: string): Promise<void> {
    await this.ensureModularStructure();
    let safeName = this.sanitizeSegmentName(name);
    if (!safeName.endsWith('.conf')) safeName += '.conf';
    await fs.writeFile(path.join(SNAPSERVER_CONFIG_DIR, safeName), content, 'utf-8');
    await this.rebuildMasterConfig();
  }

  async deleteSegment(name: string): Promise<void> {
    await this.ensureModularStructure();
    const safeName = this.sanitizeSegmentName(name);
    await fs.unlink(path.join(SNAPSERVER_CONFIG_DIR, safeName));
    await this.rebuildMasterConfig();
  }

  async setSnapserverDocRoot(docRootPath: string): Promise<void> {
    // Installing/updating snap-ctrl must NOT reset the user's configuration —
    // it should only change [http] doc_root. We therefore edit the LIVE master
    // (/etc/snapserver.conf, the file snapserver reads and the one the config
    // editor writes to) surgically and in place.
    //
    // We deliberately avoid the old base -> rebuildMasterConfig() path here: the
    // base file is only created once and never re-synced, so if the user had
    // edited their config through the UI after snap-ctrl was first installed,
    // rebuilding the master from the stale base wiped those edits. Editing the
    // live master directly guarantees only doc_root changes.
    const raw = await this.readServerConfig();

    if (raw && raw.trim().length > 20) {
      // Preserve the live config; change only doc_root.
      const updated = surgicallySetIniKey(raw, 'http', 'doc_root', docRootPath);
      await this.writeServerConfig(updated);

      // Keep the modular base in sync (if it exists) so a later pipe-source
      // rebuild carries the correct doc_root too — but never rebuild here.
      try {
        await fs.access(SNAPSERVER_CONFIG_BASE);
        const baseRaw = await fs.readFile(SNAPSERVER_CONFIG_BASE, 'utf-8');
        const baseUpdated = surgicallySetIniKey(baseRaw, 'http', 'doc_root', docRootPath);
        await fs.writeFile(SNAPSERVER_CONFIG_BASE, baseUpdated, 'utf-8');
      } catch {
        // No base file — nothing to keep in sync.
      }
      return;
    }

    // No live config to preserve (missing/empty): fall back to the modular seed.
    try {
      await this.ensureModularStructure();
      const baseRaw = await fs.readFile(SNAPSERVER_CONFIG_BASE, 'utf-8');
      const updated = surgicallySetIniKey(baseRaw, 'http', 'doc_root', docRootPath);
      await fs.writeFile(SNAPSERVER_CONFIG_BASE, updated, 'utf-8');
      await this.rebuildMasterConfig();
    } catch (error) {
      console.error('Failed to update doc_root:', error);
      throw error;
    }
  }

  async getTcpSources(): Promise<{ name: string; port: number }[]> {
    const config = await this.readServerConfigParsed();
    const sources: { name: string; port: number }[] = [];
    
    if (config.stream && config.stream.source) {
      const sourceList = Array.isArray(config.stream.source) 
        ? config.stream.source 
        : [config.stream.source as any];
        
      for (const src of sourceList) {
        const srcStr = String(src);
        if (srcStr.startsWith('tcp://')) {
          try {
            // URL parses tcp:// as a valid format usually, but might complain about missing host or format.
            // Let's use Regex for safer extraction, as URL module may sometimes fail on custom URL schemes without SLD
            const match = srcStr.match(/tcp:\/\/([^:/\s]+):(\d+)/);
            if (match) {
              const port = parseInt(match[2], 10);
              const nameMatch = srcStr.match(/[?&]name=([^&]+)/);
              const name = nameMatch ? decodeURIComponent(nameMatch[1]) : `TCP Port ${port}`;
              sources.push({ name, port });
            }
          } catch (e) {
             // Fallback
          }
        }
      }
    }
    return sources;
  }

  async resetToDefault(): Promise<void> {
    await fs.writeFile(SNAPSERVER_CONFIG_BASE, DEFAULT_SNAPSERVER_CONF, 'utf-8');
    await this.rebuildMasterConfig();
  }

  /** Apply an in-place transform to the modular base file if it exists (no rebuild). */
  private async syncBaseInPlace(transform: (content: string) => string): Promise<void> {
    try {
      await fs.access(SNAPSERVER_CONFIG_BASE);
      const baseRaw = await fs.readFile(SNAPSERVER_CONFIG_BASE, 'utf-8');
      const updated = transform(baseRaw);
      if (updated !== baseRaw) await fs.writeFile(SNAPSERVER_CONFIG_BASE, updated, 'utf-8');
    } catch {
      // No base file — nothing to keep in sync.
    }
  }

  async addStreamSource(uri: string): Promise<void> {
    // Edit the live master in place so we never revert the user's config, then
    // keep the modular base in sync (see setSnapserverDocRoot for the rationale).
    const raw = await this.readServerConfig();
    if (raw && raw.trim().length > 20) {
      const updated = surgicallyAddStreamSource(raw, uri);
      if (updated !== raw) await this.writeServerConfig(updated);
      await this.syncBaseInPlace(base => surgicallyAddStreamSource(base, uri));
      return;
    }
    // No live config to preserve — fall back to the modular seed + rebuild.
    await this.ensureModularStructure();
    const base = await fs.readFile(SNAPSERVER_CONFIG_BASE, 'utf-8');
    const updated = surgicallyAddStreamSource(base, uri);
    if (updated !== base) {
      await fs.writeFile(SNAPSERVER_CONFIG_BASE, updated, 'utf-8');
      await this.rebuildMasterConfig();
    }
  }

  async removeStreamSourceByFifo(fifoPath: string): Promise<void> {
    const raw = await this.readServerConfig();
    if (raw && raw.trim().length > 20) {
      const updated = surgicallyRemoveStreamSourcesByFifo(raw, fifoPath);
      if (updated !== raw) await this.writeServerConfig(updated);
      await this.syncBaseInPlace(base => surgicallyRemoveStreamSourcesByFifo(base, fifoPath));
      return;
    }
    await this.ensureModularStructure();
    const base = await fs.readFile(SNAPSERVER_CONFIG_BASE, 'utf-8');
    const updated = surgicallyRemoveStreamSourcesByFifo(base, fifoPath);
    if (updated !== base) {
      await fs.writeFile(SNAPSERVER_CONFIG_BASE, updated, 'utf-8');
      await this.rebuildMasterConfig();
    }
  }
}

export const configService = new ConfigService();
