import fs from 'fs/promises';
import path from 'path';

import { SnapConfigParser, SnapServerConfig } from '../utils/snapConfigParser';
import { DEFAULT_SNAPSERVER_CONF } from '../constants/defaultConfig';

// Default location on Debian
// Default locations on Debian
const SNAPSERVER_CONFIG_PATH = '/etc/snapserver.conf';
const SNAPSERVER_CONFIG_BASE = '/etc/snapserver.conf.base';
const SNAPSERVER_CONFIG_DIR = '/etc/snapserver.conf.d';

export class ConfigService {
  
  async readServerConfig(): Promise<string> {
    try {
      await fs.access(SNAPSERVER_CONFIG_PATH);
      return await fs.readFile(SNAPSERVER_CONFIG_PATH, 'utf-8');
    } catch (error) {
     console.warn(`Could not read ${SNAPSERVER_CONFIG_PATH}, returning empty.`);
     return '';
    }
  }

  async readServerConfigParsed(): Promise<SnapServerConfig> {
    const raw = await this.readServerConfig();
    return SnapConfigParser.parse(raw);
  }

  async writeServerConfigParsed(config: SnapServerConfig): Promise<void> {
    const raw = SnapConfigParser.stringify(config);
    await this.writeServerConfig(raw);
  }

  async writeServerConfig(content: string): Promise<void> {
    // If modular system is active/desired, we should probably write to base instead
    // but for compatibility with existing UI, we'll allow writing to master if requested.
    // However, the "right" way now is via segments or base.
    await fs.writeFile(SNAPSERVER_CONFIG_PATH, content, 'utf-8');
  }

  async ensureModularStructure(): Promise<void> {
    try {
      await fs.mkdir(SNAPSERVER_CONFIG_DIR, { recursive: true });
      
      try {
        await fs.access(SNAPSERVER_CONFIG_BASE);
      } catch (e) {
        // Migrate current config to base if base doesn't exist
        console.log(`Migrating ${SNAPSERVER_CONFIG_PATH} to ${SNAPSERVER_CONFIG_BASE}...`);
        const current = await this.readServerConfig();
        if (current && current.length > 50) { // arbitrary length to avoid migrating empty/broken files
          await fs.writeFile(SNAPSERVER_CONFIG_BASE, current, 'utf-8');
        } else {
          await fs.writeFile(SNAPSERVER_CONFIG_BASE, DEFAULT_SNAPSERVER_CONF, 'utf-8');
        }
      }
    } catch (error) {
      console.error('Failed to ensure modular structure:', error);
    }
  }

  async rebuildMasterConfig(): Promise<void> {
    await this.ensureModularStructure();
    
    let masterContent = '###############################################################################\n';
    masterContent += '# WARNING: THIS FILE IS AUTOMATICALLY GENERATED BY SNAPCAST MANAGER\n';
    masterContent += `# ANY MANUAL CHANGES WILL BE OVERWRITTEN. EDIT ${SNAPSERVER_CONFIG_BASE} OR SEGMENTS IN ${SNAPSERVER_CONFIG_DIR}\n`;
    masterContent += '###############################################################################\n\n';

    // 1. Read Base
    try {
      const base = await fs.readFile(SNAPSERVER_CONFIG_BASE, 'utf-8');
      masterContent += '### START BASE CONFIGURATION ###\n';
      masterContent += base;
      masterContent += '\n### END BASE CONFIGURATION ###\n\n';
    } catch (e) {
      masterContent += '# Error reading base configuration\n\n';
    }

    // 2. Read Segments
    try {
      const files = await fs.readdir(SNAPSERVER_CONFIG_DIR);
      const confFiles = files.filter(f => f.endsWith('.conf')).sort();
      
      for (const file of confFiles) {
        const content = await fs.readFile(path.join(SNAPSERVER_CONFIG_DIR, file), 'utf-8');
        masterContent += `### START SEGMENT: ${file} ###\n`;
        masterContent += content;
        masterContent += `\n### END SEGMENT: ${file} ###\n\n`;
      }
    } catch (e) {
      console.error('Error reading configuration segments:', e);
    }

    await fs.writeFile(SNAPSERVER_CONFIG_PATH, masterContent, 'utf-8');
  }

  async getSegments(): Promise<{name: string, content: string}[]> {
    await this.ensureModularStructure();
    const segments: {name: string, content: string}[] = [];
    try {
      const files = await fs.readdir(SNAPSERVER_CONFIG_DIR);
      const confFiles = files.filter(f => f.endsWith('.conf')).sort();
      
      for (const file of confFiles) {
        const content = await fs.readFile(path.join(SNAPSERVER_CONFIG_DIR, file), 'utf-8');
        segments.push({ name: file, content });
      }
    } catch (e) {
      console.error('Error listing segments:', e);
    }
    return segments;
  }

  async saveSegment(name: string, content: string): Promise<void> {
    await this.ensureModularStructure();
    if (!name.endsWith('.conf')) name += '.conf';
    await fs.writeFile(path.join(SNAPSERVER_CONFIG_DIR, name), content, 'utf-8');
    await this.rebuildMasterConfig();
  }

  async deleteSegment(name: string): Promise<void> {
    await this.ensureModularStructure();
    await fs.unlink(path.join(SNAPSERVER_CONFIG_DIR, name));
    await this.rebuildMasterConfig();
  }

  async setSnapserverDocRoot(docRootPath: string): Promise<void> {
    // When using modular system, we should probably update the BASE or a specific segment.
    // For now, let's update the BASE to keep it simple.
    try {
        await this.ensureModularStructure();
        const baseRaw = await fs.readFile(SNAPSERVER_CONFIG_BASE, 'utf-8');
        const config = SnapConfigParser.parse(baseRaw);
        if (!config.http) config.http = {};
        config.http.doc_root = docRootPath;
        const newBase = SnapConfigParser.stringify(config);
        await fs.writeFile(SNAPSERVER_CONFIG_BASE, newBase, 'utf-8');
        await this.rebuildMasterConfig();
    } catch (error) {
        // Fallback to direct write if modular structure fails (unlikely)
        const raw = await this.readServerConfig();
        const config = SnapConfigParser.parse(raw);
        if (!config.http) config.http = {};
        config.http.doc_root = docRootPath;
        await this.writeServerConfig(SnapConfigParser.stringify(config));
    }
  }

  async getTcpSources(): Promise<{ name: string; port: number }[]> {
    const config = await this.readServerConfigParsed();
    const sources: { name: string; port: number }[] = [];
    
    if (config.stream && config.stream.source) {
      const sourceList = Array.isArray(config.stream.source) 
        ? config.stream.source 
        : [config.stream.source as any];
        
      for (const src of sourceList) {
        const srcStr = String(src);
        if (srcStr.startsWith('tcp://')) {
          try {
            // URL parses tcp:// as a valid format usually, but might complain about missing host or format.
            // Let's use Regex for safer extraction, as URL module may sometimes fail on custom URL schemes without SLD
            const match = srcStr.match(/tcp:\/\/([^:/\s]+):(\d+)/);
            if (match) {
              const port = parseInt(match[2], 10);
              const nameMatch = srcStr.match(/[?&]name=([^&]+)/);
              const name = nameMatch ? decodeURIComponent(nameMatch[1]) : `TCP Port ${port}`;
              sources.push({ name, port });
            }
          } catch (e) {
             // Fallback
          }
        }
      }
    }
    return sources;
  }

  async resetToDefault(): Promise<void> {
    await fs.writeFile(SNAPSERVER_CONFIG_BASE, DEFAULT_SNAPSERVER_CONF, 'utf-8');
    await this.rebuildMasterConfig();
  }
}

export const configService = new ConfigService();
